/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PlatformMessagesRouteImport } from './routes/platform/messages'
import { Route as PlatformLoginRouteImport } from './routes/platform/login'
import { Route as PlatformLiveRouteImport } from './routes/platform/live'
import { Route as PlatformLiliRouteImport } from './routes/platform/lili'
import { Route as PlatformCommunityRouteImport } from './routes/platform/community'
import { Route as PlatformAffiliateRouteImport } from './routes/platform/affiliate'
import { Route as CoursesWeddingPhotographyRouteImport } from './routes/courses/wedding-photography'
import { Route as CoursesPhotographyFundamentalsRouteImport } from './routes/courses/photography-fundamentals'
import { Route as CoursesLightingMasteryRouteImport } from './routes/courses/lighting-mastery'
import { Route as CoursesBeautyPhotographyRouteImport } from './routes/courses/beauty-photography'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInstructorsRouteImport } from './routes/admin/instructors'
import { Route as AdminAssistantRouteImport } from './routes/admin/assistant'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as AdminCoursesSlugRouteImport } from './routes/admin/courses/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMessagesRoute = PlatformMessagesRouteImport.update({
  id: '/platform/messages',
  path: '/platform/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/platform/login',
  path: '/platform/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLiveRoute = PlatformLiveRouteImport.update({
  id: '/platform/live',
  path: '/platform/live',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLiliRoute = PlatformLiliRouteImport.update({
  id: '/platform/lili',
  path: '/platform/lili',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCommunityRoute = PlatformCommunityRouteImport.update({
  id: '/platform/community',
  path: '/platform/community',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAffiliateRoute = PlatformAffiliateRouteImport.update({
  id: '/platform/affiliate',
  path: '/platform/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesWeddingPhotographyRoute =
  CoursesWeddingPhotographyRouteImport.update({
    id: '/courses/wedding-photography',
    path: '/courses/wedding-photography',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesPhotographyFundamentalsRoute =
  CoursesPhotographyFundamentalsRouteImport.update({
    id: '/courses/photography-fundamentals',
    path: '/courses/photography-fundamentals',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesLightingMasteryRoute = CoursesLightingMasteryRouteImport.update({
  id: '/courses/lighting-mastery',
  path: '/courses/lighting-mastery',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesBeautyPhotographyRoute =
  CoursesBeautyPhotographyRouteImport.update({
    id: '/courses/beauty-photography',
    path: '/courses/beauty-photography',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/admin/instructors',
  path: '/admin/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/admin/assistant',
  path: '/admin/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/admin/courses/new',
  path: '/admin/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesSlugRoute = AdminCoursesSlugRouteImport.update({
  id: '/admin/courses/$slug',
  path: '/admin/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/beauty-photography': typeof CoursesBeautyPhotographyRoute
  '/courses/lighting-mastery': typeof CoursesLightingMasteryRoute
  '/courses/photography-fundamentals': typeof CoursesPhotographyFundamentalsRoute
  '/courses/wedding-photography': typeof CoursesWeddingPhotographyRoute
  '/platform/affiliate': typeof PlatformAffiliateRoute
  '/platform/community': typeof PlatformCommunityRoute
  '/platform/lili': typeof PlatformLiliRoute
  '/platform/live': typeof PlatformLiveRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/messages': typeof PlatformMessagesRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/beauty-photography': typeof CoursesBeautyPhotographyRoute
  '/courses/lighting-mastery': typeof CoursesLightingMasteryRoute
  '/courses/photography-fundamentals': typeof CoursesPhotographyFundamentalsRoute
  '/courses/wedding-photography': typeof CoursesWeddingPhotographyRoute
  '/platform/affiliate': typeof PlatformAffiliateRoute
  '/platform/community': typeof PlatformCommunityRoute
  '/platform/lili': typeof PlatformLiliRoute
  '/platform/live': typeof PlatformLiveRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/messages': typeof PlatformMessagesRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/beauty-photography': typeof CoursesBeautyPhotographyRoute
  '/courses/lighting-mastery': typeof CoursesLightingMasteryRoute
  '/courses/photography-fundamentals': typeof CoursesPhotographyFundamentalsRoute
  '/courses/wedding-photography': typeof CoursesWeddingPhotographyRoute
  '/platform/affiliate': typeof PlatformAffiliateRoute
  '/platform/community': typeof PlatformCommunityRoute
  '/platform/lili': typeof PlatformLiliRoute
  '/platform/live': typeof PlatformLiveRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/messages': typeof PlatformMessagesRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/courses/$slug': typeof AdminCoursesSlugRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/assistant'
    | '/admin/instructors'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/testimonials'
    | '/courses/$slug'
    | '/courses/beauty-photography'
    | '/courses/lighting-mastery'
    | '/courses/photography-fundamentals'
    | '/courses/wedding-photography'
    | '/platform/affiliate'
    | '/platform/community'
    | '/platform/lili'
    | '/platform/live'
    | '/platform/login'
    | '/platform/messages'
    | '/admin/'
    | '/courses/'
    | '/platform/'
    | '/admin/courses/$slug'
    | '/admin/courses/new'
    | '/admin/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/assistant'
    | '/admin/instructors'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/testimonials'
    | '/courses/$slug'
    | '/courses/beauty-photography'
    | '/courses/lighting-mastery'
    | '/courses/photography-fundamentals'
    | '/courses/wedding-photography'
    | '/platform/affiliate'
    | '/platform/community'
    | '/platform/lili'
    | '/platform/live'
    | '/platform/login'
    | '/platform/messages'
    | '/admin'
    | '/courses'
    | '/platform'
    | '/admin/courses/$slug'
    | '/admin/courses/new'
    | '/admin/courses'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/assistant'
    | '/admin/instructors'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/testimonials'
    | '/courses/$slug'
    | '/courses/beauty-photography'
    | '/courses/lighting-mastery'
    | '/courses/photography-fundamentals'
    | '/courses/wedding-photography'
    | '/platform/affiliate'
    | '/platform/community'
    | '/platform/lili'
    | '/platform/live'
    | '/platform/login'
    | '/platform/messages'
    | '/admin/'
    | '/courses/'
    | '/platform/'
    | '/admin/courses/$slug'
    | '/admin/courses/new'
    | '/admin/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesBeautyPhotographyRoute: typeof CoursesBeautyPhotographyRoute
  CoursesLightingMasteryRoute: typeof CoursesLightingMasteryRoute
  CoursesPhotographyFundamentalsRoute: typeof CoursesPhotographyFundamentalsRoute
  CoursesWeddingPhotographyRoute: typeof CoursesWeddingPhotographyRoute
  PlatformAffiliateRoute: typeof PlatformAffiliateRoute
  PlatformCommunityRoute: typeof PlatformCommunityRoute
  PlatformLiliRoute: typeof PlatformLiliRoute
  PlatformLiveRoute: typeof PlatformLiveRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  PlatformMessagesRoute: typeof PlatformMessagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  AdminCoursesSlugRoute: typeof AdminCoursesSlugRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/messages': {
      id: '/platform/messages'
      path: '/platform/messages'
      fullPath: '/platform/messages'
      preLoaderRoute: typeof PlatformMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/login': {
      id: '/platform/login'
      path: '/platform/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/live': {
      id: '/platform/live'
      path: '/platform/live'
      fullPath: '/platform/live'
      preLoaderRoute: typeof PlatformLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/lili': {
      id: '/platform/lili'
      path: '/platform/lili'
      fullPath: '/platform/lili'
      preLoaderRoute: typeof PlatformLiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/community': {
      id: '/platform/community'
      path: '/platform/community'
      fullPath: '/platform/community'
      preLoaderRoute: typeof PlatformCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/affiliate': {
      id: '/platform/affiliate'
      path: '/platform/affiliate'
      fullPath: '/platform/affiliate'
      preLoaderRoute: typeof PlatformAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/wedding-photography': {
      id: '/courses/wedding-photography'
      path: '/courses/wedding-photography'
      fullPath: '/courses/wedding-photography'
      preLoaderRoute: typeof CoursesWeddingPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/photography-fundamentals': {
      id: '/courses/photography-fundamentals'
      path: '/courses/photography-fundamentals'
      fullPath: '/courses/photography-fundamentals'
      preLoaderRoute: typeof CoursesPhotographyFundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/lighting-mastery': {
      id: '/courses/lighting-mastery'
      path: '/courses/lighting-mastery'
      fullPath: '/courses/lighting-mastery'
      preLoaderRoute: typeof CoursesLightingMasteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/beauty-photography': {
      id: '/courses/beauty-photography'
      path: '/courses/beauty-photography'
      fullPath: '/courses/beauty-photography'
      preLoaderRoute: typeof CoursesBeautyPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/admin/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/admin/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/admin/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$slug': {
      id: '/admin/courses/$slug'
      path: '/admin/courses/$slug'
      fullPath: '/admin/courses/$slug'
      preLoaderRoute: typeof AdminCoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesBeautyPhotographyRoute: CoursesBeautyPhotographyRoute,
  CoursesLightingMasteryRoute: CoursesLightingMasteryRoute,
  CoursesPhotographyFundamentalsRoute: CoursesPhotographyFundamentalsRoute,
  CoursesWeddingPhotographyRoute: CoursesWeddingPhotographyRoute,
  PlatformAffiliateRoute: PlatformAffiliateRoute,
  PlatformCommunityRoute: PlatformCommunityRoute,
  PlatformLiliRoute: PlatformLiliRoute,
  PlatformLiveRoute: PlatformLiveRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  PlatformMessagesRoute: PlatformMessagesRoute,
  AdminIndexRoute: AdminIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  AdminCoursesSlugRoute: AdminCoursesSlugRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
